# Generated by Django 3.2.10 on 2022-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.BigIntegerField(default=1000000, primary_key=True, serialize=False)),
                ('receiver', models.ManyToManyField(related_name='receiver', to='user.Customer')),
                ('sender', models.ManyToManyField(related_name='sender', to='user.Customer')),
            ],
        ),
    ]
