# Generated by Django 3.2.10 on 2022-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
